# Generated by Django 4.2.1 on 2023-08-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_company_cash_id_loan_account_bankings_g_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cash_id',
            new_name='cash',
        ),
    ]
