# Generated by Django 4.2.1 on 2023-08-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_rename_cash_id_company_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transactions',
            name='loan_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bank_transactions',
            name='loan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank_transactions',
            name='loan_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
