# Generated by Django 4.2.1 on 2023-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_alter_bank_transactions_banking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankings_g',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankings_g',
            name='cash_balance',
            field=models.IntegerField(default=0),
        ),
    ]
