# Generated by Django 4.2.1 on 2023-08-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_alter_bankings_g_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transactions',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
            preserve_default=False,
        ),
    ]
