# Generated by Django 4.2.1 on 2023-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_bank_transactions_loan_intrest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transactions',
            name='loan_intrest',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
