# Generated by Django 4.2.1 on 2023-08-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_bank_transactions_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashbalance', models.IntegerField(default=0)),
            ],
        ),
    ]
