# Generated by Django 4.2.1 on 2023-09-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0078_alter_bank_transactions_loan_intrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transactions',
            name='balance',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
