# Generated by Django 4.2.1 on 2023-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0079_cash_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='cash',
        ),
    ]
