# Generated by Django 4.2.1 on 2023-09-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0079_bank_transactions_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transactions',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
