# Generated by Django 4.2.1 on 2023-09-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0080_alter_bank_transactions_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_account',
            name='recieved_amount',
            field=models.IntegerField(default=0),
        ),
    ]
